name: Region
version: '${project.version}'
main: me.tewpingz.region.Region
api-version: 1.19
authors: [ TewPingz ]
description: A region plugin made for my SeniorTeam application
website: https://www.tewpingz.me
