name: Region
version: '${project.version}'
main: me.tewpingz.region.RegionPlugin
api-version: 1.19
authors: [ TewPingz ]
description: A region plugin made for my SeniorTeam application
website: https://www.tewpingz.me
commands:
  region:
    aliases: [ r ]
    description: A command that lets you setup regions and edit them